### ISSUE TITLE
Support for more GIFs!

### ISSUE THREAD

**Issue by rhussmann** [ajmath/pour-one-out#5]
This thing needs... ALL THE GIFs: https://www.google.com/search?safe=off&site=&tbm=isch&source=hp&biw=1436&bih=805&q=pour+one+out+gif&oq=pour+one+out+gif

**Comment by ajmath** [comment]
so much pour

**Comment by ajmath** [comment]
I'm open to this feature addition.  Please write up a test plan with full BDD and TDD cases and submit a planned development schedule and I'll see about working this into the project roadmap

**Comment by rhussmann** [comment]
Overcome by events.
